public class com.android.internal.os.ZygoteInit$MethodAndArgsCaller extends java.lang.Exception implements java.lang.Runnable
{
    private final java.lang.reflect.Method mMethod;
    private final java.lang.String[] mArgs;

    public void <init>(java.lang.reflect.Method, java.lang.String[])
    {
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller r0;
        java.lang.reflect.Method r1;
        java.lang.String[] r2;

        r0 := @this: com.android.internal.os.ZygoteInit$MethodAndArgsCaller;

        r1 := @parameter0: java.lang.reflect.Method;

        r2 := @parameter1: java.lang.String[];

        specialinvoke r0.<java.lang.Exception: void <init>()>();

        r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.reflect.Method mMethod> = r1;

        r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.String[] mArgs> = r2;

        return;
    }

    public void run()
    {
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller r0;
        java.lang.IllegalAccessException r1, $r7;
        java.lang.Throwable r2;
        java.lang.Object[] $r3;
        java.lang.String[] $r4;
        java.lang.reflect.Method $r5;
        java.lang.RuntimeException $r8, $r10, $r12;
        java.lang.reflect.InvocationTargetException $r9, r13;
        boolean $z0, $z1;
        java.lang.Error $r11;

        r0 := @this: com.android.internal.os.ZygoteInit$MethodAndArgsCaller;

     label1:
        $r5 = r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.reflect.Method mMethod>;

        $r3 = newarray (java.lang.Object)[1];

        $r4 = r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.String[] mArgs>;

        $r3[0] = $r4;

        virtualinvoke $r5.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, $r3);

     label2:
        goto label7;

     label3:
        $r7 := @caughtexception;

        r1 = $r7;

        $r8 = new java.lang.RuntimeException;

        specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(r1);

        throw $r8;

     label4:
        $r9 := @caughtexception;

        r13 = $r9;

        r2 = virtualinvoke r13.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getCause()>();

        $z0 = r2 instanceof java.lang.RuntimeException;

        if $z0 == 0 goto label5;

        $r12 = (java.lang.RuntimeException) r2;

        throw $r12;

     label5:
        $z1 = r2 instanceof java.lang.Error;

        if $z1 == 0 goto label6;

        $r11 = (java.lang.Error) r2;

        throw $r11;

     label6:
        $r10 = new java.lang.RuntimeException;

        specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(r13);

        throw $r10;

     label7:
        return;

        catch java.lang.IllegalAccessException from label1 to label2 with label3;
        catch java.lang.reflect.InvocationTargetException from label1 to label2 with label4;
    }
}
